Inital commit to add TensorFlow processor #84
spring-cloud-stream-app-starters/app-starters-release pull request #85
Opened 2017-04-27 22:02 UTC by tzolov

Current TensorFlow SCDF Processor project is at https://github.com/tzolov/tensorflow-spring-cloud-stream-app-starters

I have added only the core `tensorflow` processor not the `twitter-sentiment processor
`

2017-04-27 22:07 UTC, sabbyanandan commented
Thanks, @tzolov!

Hi, @artembilan @sobychacko @ericbottard - please review this at your convenience. The goal for this PR is to gather feedback and whenever it is ready, I'd like for it to be contributed to its own repo. Possibly `spring-cloud-stream-app-starters/tensorflow` - TBD.

2017-04-27 22:16 UTC, sabbyanandan commented
Actually, this commit includes only the static descriptor files. The actual project will be submitted as a PR in https://github.com/spring-cloud-stream-app-starters/tensorflow.

2017-04-28 05:49 UTC, tzolov commented
Because the  https://github.com/spring-cloud-stream-app-starters/tensorflow is empyt Github doesn't allow me to fork it. There is no button or workaround. 
Perhaps you can add an empty README to the project.

2017-04-28 09:25 UTC, jvalkeal commented
@tzolov just added empty readme, repo is now forkable.

2017-04-28 15:15 UTC, artembilan commented
This PR does not make sense without any original project.
Should be mark "On hold" or `[DON NOT MERGE YET]`

@tzolov , 
please, consider to stop PR'ing from your `master`. 
It is pretty easy to perform `git checkout -b TensorFlowProcessor` to create a new branch and switch to it directly.
That way it would be easier for us to review and merge on the our local side.
And after merging you will need only `git pull upstream master` to your local copy.
Right now you will have to do `git reset --hard upstream/master` with some other possible cleaning and resolving conflicts work.

2017-04-28 15:17 UTC, sabbyanandan commented
@artembilan: It was my fault - I suggested submitting a PR without a new repo - sorry for the confusion. @tzolov is going to drop the remaining part of PR in https://github.com/spring-cloud-stream-app-starters/tensorflow.

2017-04-28 15:24 UTC, artembilan commented
@sabbyanandan ,
thank you for taking responsibility, but that isn't an error or a fault at all, really!
I just suggest to mark the PR somehow to let other to know do not merge it by accident.

The way you suggested (this PR) we have finally that repo and it is ready for forking and pushing.
Otherwise I don't know how things would go.

E.g. I asked once about repo for the AWS Kinesis Binder, but nothing happened 😉

2017-04-28 19:12 UTC, tzolov commented
here is the PR: https://github.com/spring-cloud-stream-app-starters/tensorflow/pull/1

2017-04-28 19:16 UTC, tzolov commented
also should we discuss the review (and eventual rework) here or on the tensorflow#PR itself?

2017-04-28 19:27 UTC, artembilan commented
Thank you for update, @tzolov !
Well, we will discuss here and there, but already in the scope of particular changes.

2017-04-28 19:28 UTC, artembilan commented
I've marked this one with the `[DO NOT MEGE YET]`.
I'm fully sure that we should merge this one until that in `tensorflow`

2017-04-29 17:17 UTC, tzolov commented
@artembilan i see and completely relate with your point.  This PR shouldn't be merged until the tensorflow processor PR get resolved.

2017-05-10 21:39 UTC, artembilan requested changes

2017-05-10 21:39 UTC, artembilan commented on pom.xml
> +		<spring-cloud-starter-stream-tensorflow.version>1.2.1.BUILD-SNAPSHOT</spring-cloud-starter-stream-tensorflow.version>
I'm not sure in the purpose of this project, but I guess the version here must be `1.0.0.BUILD-SNAPSHOT`

2017-05-10 23:01 UTC, sobychacko commented
Updated the tensorflow processor version. 
LGTM 
@tzolov you covered pretty much everything needed for the docs and other metadata generation. Great work!
Here is the CI plan for the Tensorflow app starter: https://jenkins.spring.io/view/Seeds/job/spring-scst-app-starters-tensorflow-master-ci/

Merging.

2017-05-10 23:01 UTC, closed without merging

2017-05-11 06:49 UTC, tzolov commented
Great! Tanks guys!
Currently the tensorflow project contains two processors: the core `tensorflow-processor` and `twitter-sentiment-processor`, but this PR covers only the `tensorflow-processor` i believe? 
Would the `twitter-sentiment-processor` be picked somehow automatically (doesn't seem so) or
should i open another PR for the `twitter-sentiment-processor`? 
@sabbyanandan @sobychacko @artembilan WDYT?